### ISSUE TITLE
Add a whitelist enabled message

### ISSUE THREAD

**Issue by RSNFreud** [Minecrell/ServerListPlus#321] opened 2020-12-20 23:12 UTC
Hi,

Was wondering if it was possible to have it show a message when there is a whitelist on and you are not on the list?

**Comment by Minecrell** [comment] 2021-04-29 16:07
Duplicate of https://github.com/Minecrell/ServerListPlus/issues/174

**Closed by Minecrell** 2021-04-29 16:07 UTC
Labels: duplicate
