### ISSUE TITLE
Ability to use number placeholders in player max

### ISSUE THREAD

**Issue by jonthesquirrel** [Minecrell/ServerListPlus#177] opened 2017-10-28 13:05 UTC
I want to use a placeholder that gives a number, in the `Max` section of the config (instead of using `Slots`, so that the version is still displayed as valid).

I tested it with %online% in the `Max:` section and it gave an error though, so I assume that section doesn't accept placeholders?

**Comment by Minecrell** [comment] 2017-10-28 13:09
Correct. I hope to change to change that in 4.0. I realize that your request is slightly more general, but I'm going to close this as duplicate of https://github.com/Minecrell/ServerListPlus/issues/54 since adding that involves making placeholders usable for the online/max player count. I hope you don't mind :)

**Closed by Minecrell** 2017-10-28 13:09 UTC
Labels: duplicate
