### ISSUE TITLE
Displayname Parameter Feature

### ISSUE THREAD

**Issue by FireLordZuko** [Minecrell/ServerListPlus#143] opened 2016-10-23 19:49 UTC
Hello!

I really love your plugin! 👍 

I just had one small request: Could you please include a parameter called %playerdisplayname% or something similar to allow us to add the [display name - Player#getDisplayName()](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#getDisplayName()) on our server list message?

Should probably not be too hard to implement and would be great since we have quite some variety in displaynames on our server. :)

**Comment by Minecrell** [comment] 2016-10-24 12:13
Duplicate of https://github.com/Minecrell/ServerListPlus/issues/88.

The problem is essentially the following: When a player pings the server I can't get the display name directly with the method you linked, that works only when the player is actually online. That means I would need to store it for all players together with the other data.

Also some nickname / display name plugins don't properly use the display name feature, so it would probably only work for some plugins.. Thank you for your request though, I will check if I can come up with an easier way once the new version is released.

**Closed by Minecrell** 2016-10-24 12:13 UTC
Labels: duplicate
