### ISSUE TITLE
[1.16.3] Could not pass event StandardPaperServerListPingEventImpl Error

### ISSUE THREAD

**Issue by ZEROOblivious** [Minecrell/ServerListPlus#306] opened 2020-09-18 18:55 UTC
Error Logs:
https://pastebin.com/01Xq30Ha

Server /Version:
Server: Paper(197) 1.16.3-R0.1-SNAPSHOT

#303 
Reported Same issue for 1.16.1 Server.
Tagged DEV in that Thread, Creating New Thread due to Server Versions being different.

What's causing this Error? The plugin seems to be working fine?

**Comment by Minecrell** [comment] 2020-10-14 08:57
Duplicate of https://github.com/Minecrell/ServerListPlus/issues/303

**Closed by Minecrell** 2020-10-14 08:57 UTC
Labels: duplicate
