### ISSUE TITLE
isbanned returns false on bungee

### ISSUE THREAD

**Issue by Wqrld** [Minecrell/ServerListPlus#196] opened 2018-02-26 07:15 UTC
[here](https://github.com/Minecrell/ServerListPlus/blob/master/Bungee/src/main/java/net/minecrell/serverlistplus/bungee/BungeePlugin.java#L424) can you make it so slp also checks bans from plugins like litebans on bungeecord?

**Comment by Wqrld** [comment] 2018-02-26 08:00
nvm dupe of a lot of things, still want this though

**Comment by Minecrell** [comment] 2018-02-26 08:17
Duplicate of https://github.com/Minecrell/ServerListPlus/issues/102. However, see https://github.com/Minecrell/ServerListPlus/issues/195 regarding LiteBans support.

**Closed by Minecrell** 2018-02-26 08:17 UTC
Labels: duplicate
