### ISSUE TITLE
Error OnPlayerJoin

### ISSUE THREAD

**Issue by Rocologo** [Minecrell/ServerListPlus#110] opened 2016-05-28 08:07 UTC
I just got this error today. I think the player was new - (not known on my server)

> [10:02:32] [Netty Epoll Server IO #2/ERROR]: Could not pass event ServerListPingEvent to ServerListPlus v3.4.5
> org.bukkit.event.EventException
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at net.minecraft.server.v1_9_R2.PacketStatusListener.a(PacketStatusListener.java:101) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at net.minecraft.server.v1_9_R2.PacketStatusInStart.a(SourceFile:23) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at net.minecraft.server.v1_9_R2.PacketStatusInStart.a(SourceFile:8) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at net.minecraft.server.v1_9_R2.NetworkManager.a(NetworkManager.java:126) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at net.minecraft.server.v1_9_R2.NetworkManager.channelRead0(NetworkManager.java:327) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at net.minecraft.server.v1_9_R2.NetworkManager.channelRead0(NetworkManager.java:1) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib4.0.1.jar:4.0.1-b291]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 14
> 	at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:453) ~[?:1.8.0_91]
> 	at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2397) ~[?:1.8.0_91]
> 	at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2312) ~[?:1.8.0_91]
> 	at java.util.Calendar.complete(Calendar.java:2268) ~[?:1.8.0_91]
> 	at java.util.Calendar.get(Calendar.java:1826) ~[?:1.8.0_91]
> 	at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1119) ~[?:1.8.0_91]
> 	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:966) ~[?:1.8.0_91]
> 	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936) ~[?:1.8.0_91]
> 	at java.text.DateFormat.format(DateFormat.java:345) ~[?:1.8.0_91]
> 	at net.minecraft.server.v1_9_R2.UserCache$BanEntrySerializer.a(UserCache.java:299) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at net.minecraft.server.v1_9_R2.UserCache$BanEntrySerializer.serialize(UserCache.java:345) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at net.minecraft.server.v1_9_R2.UserCache$BanEntrySerializer.serialize(UserCache.java:1) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:70) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at com.google.gson.Gson.toJson(Gson.java:593) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at com.google.gson.Gson.toJson(Gson.java:572) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at com.google.gson.Gson.toJson(Gson.java:527) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at com.google.gson.Gson.toJson(Gson.java:507) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at net.minecraft.server.v1_9_R2.UserCache.c(UserCache.java:231) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at net.minecraft.server.v1_9_R2.UserCache.getProfile(UserCache.java:164) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at org.bukkit.craftbukkit.v1_9_R2.CraftProfileBanList.isBanned(CraftProfileBanList.java:84) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	at net.minecrell.serverlistplus.bukkit.BukkitPlugin.isBanned(BukkitPlugin.java:458) ~[?:?]
> 	at net.minecrell.serverlistplus.core.player.PlayerIdentity.isBanned(PlayerIdentity.java:45) ~[?:?]
> 	at net.minecrell.serverlistplus.core.status.PersonalizedStatusPatch.getMaxPlayers(PersonalizedStatusPatch.java:108) ~[?:?]
> 	at net.minecrell.serverlistplus.core.status.StatusResponse.getMaxPlayers(StatusResponse.java:141) ~[?:?]
> 	at net.minecrell.serverlistplus.bukkit.handlers.BukkitEventHandler$PingListener.onServerListPing(BukkitEventHandler.java:72) ~[?:?]
> 	at sun.reflect.GeneratedMethodAccessor431.invoke(Unknown Source) ~[?:?]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
> 	... 33 more

**Comment by Minecrell** [comment] 2016-05-28 08:12
To be honest, that looks more like it is either a Spigot bug or your `banned-players.json` is corrupted, I don't think this is caused by ServerListPlus

**Comment by Minecrell** [comment] 2016-05-31 10:17
Closing for now, don't think it is caused by SLP

**Closed by Minecrell** 2016-05-31 10:17 UTC
