### ISSUE TITLE
PremiumVanish support

### ISSUE THREAD

**Issue by NorgePlayz** [Minecrell/ServerListPlus#412] opened 2024-02-16 16:18 UTC
Can you add PremiumVanish support? When I add %online%, it still showing one player even I am vanished. And if I use %premiumvanish_playercount%, it just shows one.

**Comment by stephan-gh** [comment] 2024-02-16 18:34
This is likely a duplicate of https://github.com/Minecrell/ServerListPlus/issues/265. As I analyzed there I believe the reason that `%online%` does not work correctly is a problem in PremiumVanish. I'm open for further discussion on this, but if I remember correctly I have never received any feedback for my analysis posted in https://github.com/Minecrell/ServerListPlus/issues/265#issuecomment-542388466.

I suggest you contact the author of PremiumVanish for support and ask them to address this or comment in that issue for further discussion.

**Closed by stephan-gh** 2024-02-16 18:34 UTC
Labels: duplicate

**Comment by stephan-gh** [comment] 2024-02-16 18:36
If on Bukkit I guess you could also try the placeholder via PlaceholderAPI, it should be `{premiumvanish_playercount}` then though.
