### ISSUE TITLE
Timer placeholder.

### ISSUE THREAD

**Issue by TheIntelloBox** [Minecrell/ServerListPlus#204] opened 2018-03-27 17:57 UTC
Hey ! :D

It would be great ! For example : 48:00:00 before the sales. :D

Thanks ! :D

**Comment by Minecrell** [comment] 2018-03-27 18:20
Duplicate of https://github.com/Minecrell/ServerListPlus/issues/103

**Closed by Minecrell** 2018-03-27 18:20 UTC
Labels: duplicate
