### ISSUE TITLE
Support with PlaceholderAPI?

### ISSUE THREAD

**Issue by icedmoca** [Minecrell/ServerListPlus#247] opened 2019-05-06 06:56 UTC
I'm trying to display the whole network total with PlaceholderAPI.

PlaceholderAPI would let me do %bungee_total%

Ex: %bungee_total%/%max%

**Comment by Minecrell** [comment] 2019-05-06 14:35
Duplicate of https://github.com/Minecrell/ServerListPlus/issues/146.

SLP does not support that at the moment. The main limitation used to be that it only supported replacing for offline players, but even now it would require some refactoring to get `OfflinePlayer`s from the main thread.

tl;dr I guess it would be possible to implement now but I'm not sure I will find the motivation and time to do so.

**Closed by Minecrell** 2019-05-06 14:35 UTC
